{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import glob\n",
    "import os\n",
    "from pptx import Presentation\n",
    "import xlsxwriter\n",
    "from pptx.enum.action import PP_ACTION\n",
    "from pptx.enum.shapes import MSO_SHAPE_TYPE\n",
    "\n",
    "n=1\n",
    "image_filename=\"\"\n",
    "def write_image(shape):\n",
    "    global n\n",
    "    global image_filename\n",
    "    image = shape.image\n",
    "    # ---get image \"file\" contents---\n",
    "    image_bytes = image.blob\n",
    "    # ---make up a name for the file, e.g. 'image.jpg'---\n",
    "    image_filename = fileName_only + '_image{:03d}.{}'.format(n, image.ext)\n",
    "    n += 1\n",
    "    print(image_filename)\n",
    "    with open(image_filename, 'wb') as f:\n",
    "        f.write(image_bytes)\n",
    "\n",
    "workbook = xlsxwriter.Workbook('hmotors_ad.xlsx')\n",
    "\n",
    "for file in glob.glob(\"./*.pptx\"):\n",
    "    fileName_only = os.path.basename(file)\n",
    "\n",
    "#     print(fileName_only)\n",
    "    worksheet = workbook.add_worksheet(name = fileName_only)\n",
    "    e_row = 0\n",
    "    e_col = 0\n",
    "    n=1\n",
    "\n",
    "    prs = Presentation(file)\n",
    "\n",
    "#     slides = prs.slides\n",
    "#     for slide in slides:\n",
    "\n",
    "    for slide in prs.slides:\n",
    "        slide_num = prs.slides.index(slide)\n",
    "        if(slide_num==0): \n",
    "            continue\n",
    "        for shape in slide.shapes:\n",
    "            if shape.shape_type == MSO_SHAPE_TYPE.PICTURE:\n",
    "                write_image(shape)            \n",
    "                worksheet.write(e_row,e_col,image_filename)\n",
    "                e_col += 1\n",
    "\n",
    "            click_action = shape.click_action\n",
    "            if click_action.action == PP_ACTION.HYPERLINK:        \n",
    "                worksheet.write(e_row,e_col,click_action.hyperlink.address)\n",
    "#                 print(e_row+e_col)\n",
    "                e_row += 1\n",
    "                e_col = 0   \n",
    "            if not shape.has_table:\n",
    "                continue    \n",
    "            tbl = shape.table\n",
    "            row_count = len(tbl.rows)\n",
    "            col_count = len(tbl.columns)\n",
    "            for r in range(1, row_count):            #첫줄에 공백이 있음 & 첫 슬라의 prepared for 제거\n",
    "                for c in range(0, col_count):\n",
    "                    cell = tbl.cell(r,c)\n",
    "                    worksheet.write(e_row,e_col,cell.text)\n",
    "                    e_col += 1\n",
    "                e_row += 1\n",
    "                e_col = 0    \n",
    "\n",
    "        if(slide_num>0):                             #첫 슬라이드 제외\n",
    "            e_row += 1\n",
    "            \n",
    "            \n",
    "workbook.close()\n",
    "    "
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
